state-machines/state_machines

Changelog.md, lib/state_machines/machine_collection.rb, test/unit/machine/machine_with_static_initial_state_test.rb, test/unit/machine_collection/machine_collection_state_initialization_test.rb
This is an attempt to get both this build and state_machines-ar builds green.
Currently state_machines-ar has at least 3 issues on latest rails assuming I got this right (features that used to work before):
1. State machines initial states used to override database column defaults,
2. You could set up a field that didn't exist on the database and the state machine could still keep track of it. Helpers method would be defined on the fly and mapped to the `state` column.
3. You could override the state machine initial state by simply passing it around on initialization. e.g. `Post.new state: 'finished'`
I believe the changes here fix those tree issues on the activerecord side. However it changes the way the api for `initialize_states` work. Now if one don't want to force the initial state …
=> Better support for activerecord 4.2 initialization

lib/state_machines/machine_collection.rb, test/unit/machine_collection/machine_collection_state_initialization_test.rb
Earlier today we noticed an issue in one of our projects where the state
wouldn't be assigned on initialization when provided as a string (state
attributes are *usually* kept as a symbol by default)
This would fix the issue but probably bring some performance / security
penalties for projects running on older ruby versions
Ultimately this should also highlight the project is in a tough
situation. The `attributes` arg I had added to initialize_states was
to fix issues related to ativemodel / activerecord initialization but it
ends up making it very confusing if you look at this gem alone. I don't
understand most of it but the root idea of adding state machines to any
ruby object and on top of that work with the very specific and
complicated initialization process for both activerecord and …
=> to_sym on attributes given to MachineCollection

README.md
The first parameter to `state_machine` is incorrect in the sample code in the README.
=> Fix bug in README sample code

lib/state_machines/machine_collection.rb, lib/state_machines/transition.rb, lib/state_machines/transition_collection.rb, test/unit/transition_collection/attribute_transition_collection_by_default_test.rb, test/unit/transition_collection/transition_collection_by_default_test.rb, test/unit/transition_collection/transition_collection_test.rb, test/unit/transition_collection/transition_collection_with_transactions_test.rb, test/unit/transition_collection/transition_collection_without_transactions_test.rb
Fixed inconsistent use of `:use_transactions` (machine.rb), `:transaction` (option in transition_collection.rb), `:use_transaction` (`attr_reader` in transition_collection.rb) and standardized on `:use_transactions`.  Made `MachineCollection` and `TransitionCollection` respect the `state_machine` `:use_transactions` configuration.  Previously, the `MachineCollection` and `TransitionCollection` were operating off of hardcoded values, and ignoring the `state_machine` configuration.  Hardcoded defaults remain but are overridden if specified in the `state_machine` configuration.
In the process, added `#resolve_use_transactions` to address a corner case where homogeneous `state_machine` `:use_transactions` configurations could create indeterminate behavior.
=> Fixed inconsistent use of :use_transactions

lib/state_machines/transition_collection.rb
This is a non-breaking change to allow state_machines to meet standard behavior of ActiveRecord.save.  Specifically: test "ActiveRecord::Base#save returns nil on a rolled-back transaction"
=> Mimic ActiveRecord.save behavior on rollback.

lib/state_machines/state.rb, test/files/models/motorcycle.rb, test/functional/motorcycle_test.rb
When a sub-class clones a new copy of the machine the states get updated but the cached `StateContext` was still pointing to the old machine instance. Meaning that each `state` rule gets evaluated in the context of the parent class.
We first noticed this with ActiveRecord objects using single table inheritance. Adding validation rules in `state`s on the sub-class would cause the parent class to also apply those validations.
The added test case actually passes without the fix, but I can’t quite figure out why. Something to do with the _default definee_ for `def` in the context of a `class_eval`, I think.
In any case, `example_class_method` will cause an undefined method error if it is called on `Vehicle`, but executes correctly on `Motorcycle` with the fix applied.
=> Fix states being evaluated with wrong `owner_class` context

README.md
This PR makes the PNG badge an SVG one.
=> README: Use svg version of CodeClimate badge

lib/state_machines/machine.rb, test/files/models/driver.rb, test/functional/driver_default_nonstandard_test.rb
Fixed case when the state machine has a name differed to default, and call to `::state_machine` method triggered next time after the find initial one.
=> Fixed state machine false duplication.

lib/state_machines/integrations.rb, lib/state_machines/integrations/base.rb, test/files/integrations/vehicle.rb, test/unit/integrations/integration_matcher_test.rb, test/unit/machine/machine_with_custom_integration_test.rb
Followup to: https://github.com/state-machines/state_machines/pull/50
I was investigating into our app boot time today, and I found something interesting:
```
==================================
Mode: wall(1000)
Samples: 22 (21.43% miss rate)
GC: 2 (9.09%)
==================================
TOTAL    (pct)     SAMPLES    (pct)     FRAME
6  (27.3%)           5  (22.7%)     StateMachines::Machine#owner_class_ancestor_has_method?
5  (22.7%)           5  (22.7%)     block in StateMachines::Integrations::Base::ClassMethods#matches?
1   (4.5%)           1   (4.5%)     block in ActiveSupport::Dependencies#search_for_file
1   (4.5%)           1   (4.5%)     Hash#assert_valid_keys
1   (4.5%)           1   (4.5%)     StateMachines::NodeCollection#value
1   (4.5%)           1   (4.5%) …
```
=> Optimize Integrations::Base::ClassMethods#matches?

lib/state_machines/machine.rb, test/unit/machine/machine_with_action_defined_in_prepended_module_test.rb
`owner_class_ancestor_has_method?` search if method is already defined in one of ancestors list class.
The method searches through the list of ancestors filtering out only the classes after excluding the first
element of the list.
If a module is prepended exclude the first element
of the list( the prepended module) and then the first class return
the owner_class.
Reverse the flow so that exclude the first element after filtering out only the classes.
=> Support prepend module

lib/state_machines/event.rb, test/unit/event/event_on_failure_test.rb
When passing arguments to an event, the `after_failure` callback does not include the arguments
=> pass event args to after_failure callbacks

lib/state_machines/matcher_helpers.rb
It looks like we have a mismatch in our current example:
https://github.com/state-machines/state_machines/blob/d25ae3dfa3a66a2ba1006debf7a4a9cb3aedc327/lib/state_machines/matcher_helpers.rb#L36-L49
I can't see the `:parked` state anywhere in the example. It seems we wanted to have `:idling` instead of `:parked`, doesn't it?
=> docs: fix example for the `same` helper method

README.md
The code example doesn't need to define the same transition twice.
=> Remove duplicate line from code example

.github/workflows/engines.yml, .github/workflows/ruby.yml, test/unit/eval_helper/eval_helpers_symbol_tainted_method_test.rb
Also updates the checkout action version constraint to v3 to eliminate a Node 12 warning in actions.
To get the specs running green I had to conditionally disable the `taint` test, since that method no longer exists in Ruby 3.2+
Runs green on my fork.
=> Add Ruby 3.2 to the CI matrix

.github/workflows/ruby.yml, LICENSE.txt, state_machines.gemspec
This will allow us to use new ruby syntax exclusively
I will release this version after merging #94
cc @julitrows
=> feat: Drop support to ruby prior 3.0

.gitignore, lib/state_machines/event.rb, test/files/models/hybrid_car.rb, test/functional/hybrid_car_test.rb
Some time ago I opened this issue: https://github.com/state-machines/state_machines/issues/82
It was closed because everything seemed to be fine.
However https://github.com/state-machines/state_machines/issues/82#issuecomment-1569076464 by @jmanian made me think about the issue again. Instead of providing a test rails application that triggers the problem as I did when I opened the issue, this time I thought of getting inside the gem and try to solve it.
So I created some functional specs (see [HybridCar](https://github.com/julitrows/state_machines/blob/2ff8e4e53ca9cfd250d635dc33714cf6c2a0baf3/test/files/models/hybrid_car.rb) and [HybridCarTest](https://github.com/julitrows/state_machines/blob/2ff8e4e53ca9cfd250d635dc33714cf6c2a0baf3/test/functional/hybrid_car_test.rb)) that would reflect …
=> Attempting to solve the Ruby 2.7 Kwarg warnings/3.0 issue with kwargs in unsafe/bang methods

test/functional/auto_shop_available_test.rb, test/functional/auto_shop_busy_test.rb, test/functional/car_backing_up_test.rb, test/functional/car_test.rb, test/functional/driver_default_nonstandard_test.rb, test/functional/hybrid_car_test.rb, test/functional/motorcycle_test.rb, test/functional/traffic_light_caution_test.rb, test/functional/traffic_light_proceed_test.rb, test/functional/traffic_light_stop_test.rb, test/functional/vehicle_first_gear_test.rb, test/functional/vehicle_idling_test.rb, test/functional/vehicle_locked_test.rb, test/functional/vehicle_parked_test.rb, test/functional/vehicle_repaired_test.rb, test/functional/vehicle_second_gear_test.rb, test/functional/vehicle_stalled_test.rb, test/functional/vehicle_test.rb, test/functional/vehicle_third_gear_test.rb, test/functional/vehicle_unsaved_test.rb, test/functional/vehicle_with_event_attributes_test.rb, test/functional/vehicle_with_parallel_events_test.rb, test/test_helper.rb
The MiniTest name space has been deprecated since minitest 5.19 and causes errors with ruby3.3
=> Replace old MiniTest namespace by Minitest

.github/workflows/ruby.yml, Gemfile, test/test_helper.rb, test/unit/machine/machine_with_event_matchers_test.rb, test/unit/machine/machine_with_state_matchers_test.rb
The syntax of the hash.inspect changed in ruby 3.4 , so i updated the tests
=> chore: test ruby 3.4

lib/state_machines/eval_helpers.rb, lib/state_machines/machine.rb, test/test_helper.rb, test/unit/eval_helper/eval_helpers_string_test.rb
Symbols are immutable and only created once, while interpolated strings create new objects for each method call
This change is especially beneficial for code that gets executed frequently in hot paths of the application, as it reduces garbage collection pressure and improves overall performance.
=> fix: use symbol syntax for instance variable checks

README.md, Rakefile, bin/console, bin/setup, lib/state_machines.rb, lib/state_machines/branch.rb, lib/state_machines/event.rb, lib/state_machines/machine.rb, lib/state_machines/state.rb, lib/state_machines/stdio_renderer.rb, test/unit/stdio_renderer_test.rb
In this PR we introduces a default STDIORenderer for debugging state machines without external dependencies. 
The draw methods in Event, Branch, State, and Machine now use the configured renderer by default. 
Backward compatibility was kept since graphiz gem just overwrite the draw method for now. 
I will change it later.
=> feat: introduce STDIO renderer

lib/state_machines/transition.rb
Ported forward from https://github.com/state-machines/state_machines/pull/118
Currently the only way to skip "running the action" is to send `false` as the final positional argument but that's impossible with hash-based options.
This PR adds a `run_action` key in addition to the traditional positional argument handling.
=> Add run_action as a hash option

README.md, lib/state_machines/transition.rb
- Formatting changes (makes it easier to copy commands)
- Add example for passing arguments to transition callbacks
- Add code docs for `run_action`
=> Update README and run_action docs

lib/state_machines/state.rb
PR #114 added conflict checking but didn't check the ignore_method_conflictsflag before showing warnings.
This fix ensures State#add_predicate respects the StateMachines::Machine.ignore_method_conflicts setting, making it consistent with Machine#define_helper behavior.
Closes #135
=> feat: respect ignore_method_conflicts in State#add_predicate

README.md, lib/state_machines/branch.rb, lib/state_machines/event.rb, test/unit/branch/branch_with_invalid_state_guards_test.rb, test/unit/branch/branch_with_state_guards_test.rb, test/unit/event/event_transitions_test.rb, test/unit/integration/guards_async_integration_test.rb, test/unit/machine/machine_with_transitions_test.rb
Introduces a new set of declarative guards for transitions that depend on the state of other state machines within the same object.
This allows for more complex and robust system modeling where the behavior of one component can be explicitly tied to the state of another, moving logic from helper methods into the state machine definition itself.
New transition options:
- :if_state
- :unless_state
- :if_all_states
- :unless_all_states
- :if_any_state
- :unless_any_state
Example:
event :fire_torpedo, if_state: { bay_doors: :open }
=> feat: Add coordinated state management guards

lib/state_machines/transition.rb, test/unit/transition/transition_thread_current_preservation_test.rb
This PR fixes issue #152 where `Thread.current` storage loses object identity when state machine transitions use Fibers. This was causing problems for applications that rely on Thread.current storage patterns.
In Ruby 3+, `Thread.current[]` provides **fiber-local storage**, not thread-local storage. When state_machines creates Fibers for callback execution (used for pausable transitions and async mode), each new Fiber starts with empty fiber-local storage. This breaks patterns like:
```ruby
Thread.current[:store] ||= []
```
Each callback would see `nil` and create a new array, breaking object identity across callbacks.
The fix captures and restores Thread.current storage when creating Fibers for callback execution:
1. **Before creating a Fiber**: Capture all Thread.current keys/values …
=> fix: preserve Thread.current storage across Fiber boundaries (#152)
